spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-flyway?autoReconnect=true&useSSL=false&serverTimezone=JST
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
